### ISSUE TITLE
[Feature request] Button to reset the proof

### ISSUE THREAD

**Issue by raulpy271** [mrieppel/fitch#1]
Hi @mrieppel, 

I think that is util to have a button to start a new prof, it's better than refresh the page. What's your opinion?

**Comment by mrieppel** [comment]
Thanks for the suggestion.  I agree that using refresh to start a new proof is a little clunky, I may take that up in the future.  I'm not developing fitchjs any more, I'm using FitchFX for my class now: https://github.com/mrieppel/FitchFX

**Comment by raulpy271** [comment]
I read a little bit of the code, Can I make the changes and send a pull request to this repo?

**Comment by mrieppel** [comment]
Sure, you can send me a pull request with the button added.
