### ISSUE TITLE
[Bug] The function `setup_proof` access an element that doesn't exist

### ISSUE THREAD

**Issue by raulpy271** [mrieppel/fitch#2]
In the commit c5154a477f2cdcf43e3a685877ab5f1353f462ce the element with the id `phi251msg` has deleted, But you forgot to delete the code that manipulates him: https://github.com/mrieppel/fitchjs/blob/c5154a477f2cdcf43e3a685877ab5f1353f462ce/script/userio.js#L71

So, when the user starts a proof an exception is raised.

**Comment by mrieppel** [comment]
Thanks for spotting this!  I deleted the reference to the phi251msg element.
