### ISSUE TITLE
I go to website click begin and already get error with default example

### ISSUE THREAD

**Issue by lfmunoz** [mrieppel/fitch#4]
ERROR: conclusion is not well formed.

**Comment by mrieppel** [comment]
The "default example" is just a placeholder element, not an actual input value, see: 

https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder

You have to type a formula into the input field first, and then click "begin proof".  I can see that this could be confusing to some users though, I may change it the next time I update the code.

**Comment by mrieppel** [comment]
I've now updated the code to include a clearer error message when the user begins without entering a conclusion.
